### ISSUE TITLE
tool: maker

### ISSUE THREAD

**Issue by nathandunn** [galaxy-genome-annotation/docker-galaxy-genome-annotation#15]
http://www.yandell-lab.org/software/maker.html

http://gmod.org/wiki/MAKER

> MAKER is not available for commercial use without a license. Those wishing to license MAKER for commercial use should contact Aaron Duffy at the University of Utah TVC to discuss your needs.

I think we just display this for the tool somewhere so it is up to the user to handle any licensing issues.  

Also, we could have a "license" tool piece that will generate a license directly:

http://yandell.topaz.genetics.utah.edu/cgi-bin/maker_license.cgi

Maker-P might be another option:  http://www.yandell-lab.org/software/maker-p.html

The Yandell  Lab may have additional licensing suggestions as well.

**Comment by hexylena** [comment]
This is not possible I'm afraid.

The IUC has hit this issue with numerous tools, most importantly we cannot package it for Galaxy. It isn't a question of building a UI and having that check for license, we do not have the rights to distribute the packaged software. It would cause us legal troubles.
(Just documenting the rationale for why I'm closing this reuqest that someone raised in our BoF. If Maker is ever open sourced we can revisit this.)
