### ISSUE TITLE
Integrate Apollo

### ISSUE THREAD

**Issue by hexylena** [galaxy-genome-annotation/docker-galaxy-genome-annotation#2]

**Comment by hexylena** [comment]
@bgruening would you mind assigning this to me please?

**Comment by bgruening** [comment]
I assign you to everything as soon as you promise me to not burn out :)

**Comment by hexylena** [comment]
Retitled. 

Given that https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment is now pretty much done, I'm getting around to the last thing on the todo list, add apollo to this image so it's actually legitimately useful for annotation.

Currently the apollo tools are installed in a very ugly/manual way. Here are some options:
- install the apollo tools as currently done, many extra files in the repo, but since all of this configuration is highly specific to this repo, it makes some sense.
- create a small toolshed repository with some of that configuration built in, but caution people not to use it as it will only be appropriate to this image
- wait until Galaxy supports remote services (kv store stuff) and I merge my apollo tools to IUC ownership.

Thoughts?
