### ISSUE TITLE
Tool: Gemini Genome Annotation

### ISSUE THREAD

**Issue by nathandunn** [galaxy-genome-annotation/docker-galaxy-genome-annotation#20]
Someone had brought this up for doing genome annotation:

https://gemini.readthedocs.io/en/latest/

**Comment by nathandunn** [comment]
Also handles genetic variation as well.

**Comment by Eduardo-Alves** [comment]
it should be possible to add all annotations for variants to a gemini database and then write an sql query to create a gff with the annotation in the attributes

**Comment by abretaud** [comment]
There are some wrappers for Gemini [in IUC](https://github.com/galaxyproject/tools-iuc/tree/master/tools/gemini), is anything missing now?

**Comment by nathandunn** [comment]
@abretaud   Its probably good if those could be readily added to the pipeline.  Close it?
