### ISSUE TITLE
Tool: add Maker annotation pipeline

### ISSUE THREAD

**Issue by abretaud** [galaxy-genome-annotation/docker-galaxy-genome-annotation#21]
Maker homepage: http://www.yandell-lab.org/software/maker.html
There is something strange about the license: 

>  MAKER is available for academic use under either the Artistic License 2.0 developed by the Perl Foundation or the GNU General Public License developed by the Free Software Foundation.
> 
> MAKER is not available for commercial use without a license. Those wishing to license MAKER for commercial use should contact Aaron Duffy at the University of Utah TVC to discuss your needs. 

But, discussed with Carson Holt who is ok for packaging it.

There is already a brew recipe there: https://github.com/Homebrew/homebrew-science/blob/master/maker.rb

And the GPL-licensed code can be downloaded directly there: http://yandell.topaz.genetics.utah.edu/maker_downloads/static/maker-2.31.9.tgz

I intend to work on a conda recipe in the coming weeks

**Comment by abretaud** [comment]
Done!

**Comment by hexylena** [comment]
:tada:
