### ISSUE TITLE
Merge with erasche/docker-galaxy-annotation?

### ISSUE THREAD

**Issue by abretaud** [galaxy-genome-annotation/docker-galaxy-genome-annotation#7]
Is there plan to merge this image with https://github.com/erasche/docker-galaxy-annotation?
It looks like the main difference is the apollo tools which are only in @erasche's repo
I'd like to add the tripal tools as well (if you're ok of course!)

**Comment by bgruening** [comment]
Jupp, there are plans to merge both. Not sure in which direction, but I'm open to work on it.

**Comment by hexylena** [comment]
The plan is to merge this one, since it has everything configured more properly than my old image:
https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment

**Comment by hexylena** [comment]
and has a lot more features.

**Comment by abretaud** [comment]
Hum, not sure to understand, I was talking about the galaxy Dockerfile, but https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment is the docker-compose.yml + conf files

Or maybe you wanted to talk about https://github.com/galaxy-genome-annotation/docker-galaxy-annotation?

**Comment by hexylena** [comment]
I was thinking of merging all the things into one "GGA Galaxy Image", but you are right, I was definitely thinking of a `docker-compose.yml`.
